/*
Copyright (c) 2025  Blue Robotics North Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
//Put common constants, and other definitions here
//and specify the module key
@module_key(0x4244)
module ::Blueberry::Devices {
	//a handy sequence of 32-bit floats. This is like an array but variable length
	typedef sequence <float> FloatSequence;
	
	
	//an enum to specify a port pin
	//this is constructed with the top nibble representing the port and the bottom nibble the pin number
	enum PortPinEnum : uint8 {
		GPIO_A0_PIN = 	0x00,
		GPIO_A1_PIN = 	0x01,
		GPIO_A2_PIN = 	0x02,
		GPIO_A3_PIN = 	0x03,
		GPIO_A4_PIN = 	0x04,
		GPIO_A5_PIN = 	0x05,
		GPIO_A6_PIN =	0x06,
		GPIO_A7_PIN = 	0x07,
		GPIO_A8_PIN = 	0x08,
		GPIO_A9_PIN = 	0x09,
		GPIO_A10_PIN =	0x0a,
		GPIO_A11_PIN =	0x0b,
		GPIO_A12_PIN =	0x0c,
		GPIO_A13_PIN =	0x0d,
		GPIO_A14_PIN =	0x0e,
		GPIO_A15_PIN =	0x0f,
		GPIO_B0_PIN =  	0x10,
		GPIO_B1_PIN =  	0x11,
		GPIO_B2_PIN =  	0x12,
		GPIO_B3_PIN =  	0x13,
		GPIO_B4_PIN =  	0x14,
		GPIO_B5_PIN =  	0x15,
		GPIO_B6_PIN = 	0x16,
		GPIO_B7_PIN =  	0x17,
		GPIO_B8_PIN =  	0x18,
		GPIO_B9_PIN =  	0x19,
		GPIO_B10_PIN = 	0x1a,
		GPIO_B11_PIN = 	0x1b,
		GPIO_B12_PIN = 	0x1c,
		GPIO_B13_PIN = 	0x1d,
		GPIO_B14_PIN = 	0x1e,
		GPIO_B15_PIN = 	0x1f,
		GPIO_C0_PIN =  	0x20,
		GPIO_C1_PIN =  	0x21,
		GPIO_C2_PIN =  	0x22,
		GPIO_C3_PIN =  	0x23,
		GPIO_C4_PIN =  	0x24,
		GPIO_C5_PIN =  	0x25,
		GPIO_C6_PIN =   0x26,
		GPIO_C7_PIN =  	0x27,
		GPIO_C8_PIN =  	0x28,
		GPIO_C9_PIN =  	0x29,
		GPIO_C10_PIN = 	0x2a,
		GPIO_C11_PIN = 	0x2b,
		GPIO_C12_PIN = 	0x2c,
		GPIO_C13_PIN = 	0x2d,
		GPIO_C14_PIN = 	0x2e,
		GPIO_C15_PIN = 	0x2f,

		GPIO_D0_PIN  =   0x30,
		GPIO_D1_PIN  =   0x31,
		GPIO_D2_PIN  =   0x32,
		GPIO_D3_PIN  =   0x33,
		GPIO_D4_PIN  =   0x34,
		GPIO_D5_PIN  =   0x35,
		GPIO_D6_PIN  =   0x36,
		GPIO_D7_PIN  =   0x37,
		GPIO_D8_PIN  =   0x38,
		GPIO_D9_PIN  =   0x39,
		GPIO_D10_PIN  =  0x3a,
		GPIO_D11_PIN  =  0x3b,
		GPIO_D12_PIN  =  0x3c,
		GPIO_D13_PIN  =  0x3d,
		GPIO_D14_PIN  =  0x3e,
		GPIO_D15_PIN  =  0x3f,
		
		GPIO_E0_PIN  =   0x40,
		GPIO_E1_PIN  =   0x41,
		GPIO_E2_PIN  =   0x42,
		GPIO_E3_PIN  =   0x43,
		GPIO_E4_PIN  =   0x44,
		GPIO_E5_PIN  =   0x45,
		GPIO_E6_PIN  =   0x46,
		GPIO_E7_PIN  =   0x47,
		GPIO_E8_PIN  =   0x48,
		GPIO_E9_PIN  =   0x49,
		GPIO_E10_PIN  =  0x4a,
		GPIO_E11_PIN  =  0x4b,
		GPIO_E12_PIN  =  0x4c,
		GPIO_E13_PIN  =  0x4d,
		GPIO_E14_PIN  =  0x4e,
		GPIO_E15_PIN  =  0x4f,
		
		GPIO_F0_PIN  =   0x50,
		GPIO_F1_PIN  =   0x51,
		GPIO_F2_PIN  =   0x52,
		GPIO_F3_PIN  =   0x53,
		GPIO_F4_PIN  =   0x54,
		GPIO_F5_PIN  =   0x55,
		GPIO_F6_PIN  =   0x56,
		GPIO_F7_PIN  =   0x57,
		GPIO_F8_PIN  =   0x58,
		GPIO_F9_PIN  =   0x59,
		GPIO_F10_PIN  =  0x5a,
		GPIO_F11_PIN  =  0x5b,
		GPIO_F12_PIN  =  0x5c,
		GPIO_F13_PIN  =  0x5d,
		GPIO_F14_PIN  =  0x5e,
		GPIO_F15_PIN  =  0x5f,
		
		GPIO_G0_PIN  =   0x60,
		GPIO_G1_PIN  =   0x61,
		GPIO_G2_PIN  =   0x62,
		GPIO_G3_PIN  =   0x63,
		GPIO_G4_PIN  =   0x64,
		GPIO_G5_PIN  =   0x65,
		GPIO_G6_PIN  =   0x66,
		GPIO_G7_PIN  =   0x67,
		GPIO_G8_PIN  =   0x68,
		GPIO_G9_PIN  =   0x69,
		GPIO_G10_PIN  =  0x6a,
		GPIO_G11_PIN  =  0x6b,
		GPIO_G12_PIN  =  0x6c,
		GPIO_G13_PIN  =  0x6d,
		GPIO_G14_PIN  =  0x6e,
		GPIO_G15_PIN  =  0x6f,
		
		GPIO_H0_PIN  =   0x70,
		GPIO_H1_PIN  =   0x71,
		GPIO_H2_PIN  =   0x72,
		GPIO_H3_PIN  =   0x73,
		GPIO_H4_PIN  =   0x74,
		GPIO_H5_PIN  =   0x75,
		GPIO_H6_PIN  =   0x76,
		GPIO_H7_PIN  =   0x77,
		GPIO_H8_PIN  =   0x78,
		GPIO_H9_PIN  =   0x79,
		GPIO_H10_PIN  =  0x7a,
		GPIO_H11_PIN  =  0x7b,
		GPIO_H12_PIN  =  0x7c,
		GPIO_H13_PIN  =  0x7d,
		GPIO_H14_PIN  =  0x7e,
		GPIO_H15_PIN  =  0x7f,
		
		GPIO_I0_PIN  =   0x80,
		GPIO_I1_PIN  =   0x81,
		GPIO_I2_PIN  =   0x82,
		GPIO_I3_PIN  =   0x83,
		GPIO_I4_PIN  =   0x84,
		GPIO_I5_PIN  =   0x85,
		GPIO_I6_PIN  =   0x86,
		GPIO_I7_PIN  =   0x87,
		GPIO_I8_PIN  =   0x88,
		GPIO_I9_PIN  =   0x89,
		GPIO_I10_PIN  =  0x8a,
		GPIO_I11_PIN  =  0x8b,
		GPIO_I12_PIN  =  0x8c,
		GPIO_I13_PIN  =  0x8d,
		GPIO_I14_PIN  =  0x8e,
		GPIO_I15_PIN  =  0x8f,


		GPIO_NULL_PIN = 0xff   
	};
};
