/*
Copyright (c) 2025  Blue Robotics North Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/


module ::Blueberry::Devices {

    enum I2cDevBb : uint8 {
        I2CNULL_DEV = -1,
        I2C1_DEV = 0,
        I2C2_DEV = 1,
        I2C3_DEV = 2,
        I2C4_DEV = 3,
    };

    typedef sequence <uint32> I2cTransactionData;

    // A message to define an SPI transaction to be sent out
    @message_key(0x26ed)
    @topic("blueberry/devices/{device_type}/{nid}/spi-transaction")
    message SpiTransactionMessage {
        I2cDevBb i2cDev; // The SPI device for the SPI transaction
		uint8 i2cAddr;

        uint16 numTxBytes;
        uint16 numRxBytes;
        int32 transactionId; // Unique ID for the transaction

        I2cTransactionData transactionData; // Data to send
    };
};
